- name: GitHub Webhook Rulebook
  hosts: localhost
  sources:
    - ansible.eda.webhook:
        token: 2fff44af85ae61c8bd376ba70387f68c5d94938a
  rules:
    - name: React to GitHub Push
      condition: event.payload.action == "opened"
      action:
        run_job_template:
          name: vm  # your AAP job template name
          organization: Default
          extra_vars:
            event: "{{ event }}"
